### ISSUE TITLE
Request for article ： Efficient Representation Learning for Inner Speech Domain Generalization

### ISSUE THREAD

**Issue by tutou-pifeng** [NgHanWei/Domain_Generalisation_Inner_Speech_Classification#1]
I'm hoping for the article used for learning.
I can't find freely it in network.

**Comment by NgHanWei** [comment]
Apologies for the late response, you may find the article in the link below for your reference :)

https://drive.google.com/file/d/18rIYUSi8xKSvV1FohUmYnZJwmOALb3xV/view?usp=drive_link
